#!/usr/bin/env bash

set -euo pipefail

ovs_v_up="/etc/ovs/ovs_vbrg0_ifup"
ovs_v_down="/etc/ovs/ovs_vbrg0_ifdown"

qemu-system-x86_64 --enable-kvm -cpu host \
    -cdrom /srv/isomirror/bmoar/kali-i386.iso \
    -boot order=d /srv/vms/rop32.img -m 4G \
    -device e1000,netdev=veth0,mac=DE:AD:69:$(printf '%02X:%02X:%02X' $[RANDOM%256] $[RANDOM%256] $[RANDOM%256]) \
    -netdev tap,id=veth0,script=$ovs_v_up,downscript=$ovs_v_down
